# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.9

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /home/alon/Downloads/clion-2017.3.2/bin/cmake/bin/cmake

# The command to remove a file.
RM = /home/alon/Downloads/clion-2017.3.2/bin/cmake/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = "/home/alon/Downloads/Untitled Folder"

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = "/home/alon/Downloads/Untitled Folder"

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/home/alon/Downloads/clion-2017.3.2/bin/cmake/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/home/alon/Downloads/clion-2017.3.2/bin/cmake/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start "/home/alon/Downloads/Untitled Folder/CMakeFiles" "/home/alon/Downloads/Untitled Folder/CMakeFiles/progress.marks"
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start "/home/alon/Downloads/Untitled Folder/CMakeFiles" 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named Reversi

# Build rule for target.
Reversi: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Reversi
.PHONY : Reversi

# fast build rule for target.
Reversi/fast:
	$(MAKE) -f CMakeFiles/Reversi.dir/build.make CMakeFiles/Reversi.dir/build
.PHONY : Reversi/fast

#=============================================================================
# Target rules for targets named server

# Build rule for target.
server: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 server
.PHONY : server

# fast build rule for target.
server/fast:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/build
.PHONY : server/fast

src/client/AIPlayer.o: src/client/AIPlayer.cpp.o

.PHONY : src/client/AIPlayer.o

# target to build an object file
src/client/AIPlayer.cpp.o:
	$(MAKE) -f CMakeFiles/Reversi.dir/build.make CMakeFiles/Reversi.dir/src/client/AIPlayer.cpp.o
.PHONY : src/client/AIPlayer.cpp.o

src/client/AIPlayer.i: src/client/AIPlayer.cpp.i

.PHONY : src/client/AIPlayer.i

# target to preprocess a source file
src/client/AIPlayer.cpp.i:
	$(MAKE) -f CMakeFiles/Reversi.dir/build.make CMakeFiles/Reversi.dir/src/client/AIPlayer.cpp.i
.PHONY : src/client/AIPlayer.cpp.i

src/client/AIPlayer.s: src/client/AIPlayer.cpp.s

.PHONY : src/client/AIPlayer.s

# target to generate assembly for a file
src/client/AIPlayer.cpp.s:
	$(MAKE) -f CMakeFiles/Reversi.dir/build.make CMakeFiles/Reversi.dir/src/client/AIPlayer.cpp.s
.PHONY : src/client/AIPlayer.cpp.s

src/client/BasicGameRules.o: src/client/BasicGameRules.cpp.o

.PHONY : src/client/BasicGameRules.o

# target to build an object file
src/client/BasicGameRules.cpp.o:
	$(MAKE) -f CMakeFiles/Reversi.dir/build.make CMakeFiles/Reversi.dir/src/client/BasicGameRules.cpp.o
.PHONY : src/client/BasicGameRules.cpp.o

src/client/BasicGameRules.i: src/client/BasicGameRules.cpp.i

.PHONY : src/client/BasicGameRules.i

# target to preprocess a source file
src/client/BasicGameRules.cpp.i:
	$(MAKE) -f CMakeFiles/Reversi.dir/build.make CMakeFiles/Reversi.dir/src/client/BasicGameRules.cpp.i
.PHONY : src/client/BasicGameRules.cpp.i

src/client/BasicGameRules.s: src/client/BasicGameRules.cpp.s

.PHONY : src/client/BasicGameRules.s

# target to generate assembly for a file
src/client/BasicGameRules.cpp.s:
	$(MAKE) -f CMakeFiles/Reversi.dir/build.make CMakeFiles/Reversi.dir/src/client/BasicGameRules.cpp.s
.PHONY : src/client/BasicGameRules.cpp.s

src/client/Board.o: src/client/Board.cpp.o

.PHONY : src/client/Board.o

# target to build an object file
src/client/Board.cpp.o:
	$(MAKE) -f CMakeFiles/Reversi.dir/build.make CMakeFiles/Reversi.dir/src/client/Board.cpp.o
.PHONY : src/client/Board.cpp.o

src/client/Board.i: src/client/Board.cpp.i

.PHONY : src/client/Board.i

# target to preprocess a source file
src/client/Board.cpp.i:
	$(MAKE) -f CMakeFiles/Reversi.dir/build.make CMakeFiles/Reversi.dir/src/client/Board.cpp.i
.PHONY : src/client/Board.cpp.i

src/client/Board.s: src/client/Board.cpp.s

.PHONY : src/client/Board.s

# target to generate assembly for a file
src/client/Board.cpp.s:
	$(MAKE) -f CMakeFiles/Reversi.dir/build.make CMakeFiles/Reversi.dir/src/client/Board.cpp.s
.PHONY : src/client/Board.cpp.s

src/client/ConsoleDisplay.o: src/client/ConsoleDisplay.cpp.o

.PHONY : src/client/ConsoleDisplay.o

# target to build an object file
src/client/ConsoleDisplay.cpp.o:
	$(MAKE) -f CMakeFiles/Reversi.dir/build.make CMakeFiles/Reversi.dir/src/client/ConsoleDisplay.cpp.o
.PHONY : src/client/ConsoleDisplay.cpp.o

src/client/ConsoleDisplay.i: src/client/ConsoleDisplay.cpp.i

.PHONY : src/client/ConsoleDisplay.i

# target to preprocess a source file
src/client/ConsoleDisplay.cpp.i:
	$(MAKE) -f CMakeFiles/Reversi.dir/build.make CMakeFiles/Reversi.dir/src/client/ConsoleDisplay.cpp.i
.PHONY : src/client/ConsoleDisplay.cpp.i

src/client/ConsoleDisplay.s: src/client/ConsoleDisplay.cpp.s

.PHONY : src/client/ConsoleDisplay.s

# target to generate assembly for a file
src/client/ConsoleDisplay.cpp.s:
	$(MAKE) -f CMakeFiles/Reversi.dir/build.make CMakeFiles/Reversi.dir/src/client/ConsoleDisplay.cpp.s
.PHONY : src/client/ConsoleDisplay.cpp.s

src/client/GamePlay.o: src/client/GamePlay.cpp.o

.PHONY : src/client/GamePlay.o

# target to build an object file
src/client/GamePlay.cpp.o:
	$(MAKE) -f CMakeFiles/Reversi.dir/build.make CMakeFiles/Reversi.dir/src/client/GamePlay.cpp.o
.PHONY : src/client/GamePlay.cpp.o

src/client/GamePlay.i: src/client/GamePlay.cpp.i

.PHONY : src/client/GamePlay.i

# target to preprocess a source file
src/client/GamePlay.cpp.i:
	$(MAKE) -f CMakeFiles/Reversi.dir/build.make CMakeFiles/Reversi.dir/src/client/GamePlay.cpp.i
.PHONY : src/client/GamePlay.cpp.i

src/client/GamePlay.s: src/client/GamePlay.cpp.s

.PHONY : src/client/GamePlay.s

# target to generate assembly for a file
src/client/GamePlay.cpp.s:
	$(MAKE) -f CMakeFiles/Reversi.dir/build.make CMakeFiles/Reversi.dir/src/client/GamePlay.cpp.s
.PHONY : src/client/GamePlay.cpp.s

src/client/GameRules.o: src/client/GameRules.cpp.o

.PHONY : src/client/GameRules.o

# target to build an object file
src/client/GameRules.cpp.o:
	$(MAKE) -f CMakeFiles/Reversi.dir/build.make CMakeFiles/Reversi.dir/src/client/GameRules.cpp.o
.PHONY : src/client/GameRules.cpp.o

src/client/GameRules.i: src/client/GameRules.cpp.i

.PHONY : src/client/GameRules.i

# target to preprocess a source file
src/client/GameRules.cpp.i:
	$(MAKE) -f CMakeFiles/Reversi.dir/build.make CMakeFiles/Reversi.dir/src/client/GameRules.cpp.i
.PHONY : src/client/GameRules.cpp.i

src/client/GameRules.s: src/client/GameRules.cpp.s

.PHONY : src/client/GameRules.s

# target to generate assembly for a file
src/client/GameRules.cpp.s:
	$(MAKE) -f CMakeFiles/Reversi.dir/build.make CMakeFiles/Reversi.dir/src/client/GameRules.cpp.s
.PHONY : src/client/GameRules.cpp.s

src/client/HumanConsolePlayer.o: src/client/HumanConsolePlayer.cpp.o

.PHONY : src/client/HumanConsolePlayer.o

# target to build an object file
src/client/HumanConsolePlayer.cpp.o:
	$(MAKE) -f CMakeFiles/Reversi.dir/build.make CMakeFiles/Reversi.dir/src/client/HumanConsolePlayer.cpp.o
.PHONY : src/client/HumanConsolePlayer.cpp.o

src/client/HumanConsolePlayer.i: src/client/HumanConsolePlayer.cpp.i

.PHONY : src/client/HumanConsolePlayer.i

# target to preprocess a source file
src/client/HumanConsolePlayer.cpp.i:
	$(MAKE) -f CMakeFiles/Reversi.dir/build.make CMakeFiles/Reversi.dir/src/client/HumanConsolePlayer.cpp.i
.PHONY : src/client/HumanConsolePlayer.cpp.i

src/client/HumanConsolePlayer.s: src/client/HumanConsolePlayer.cpp.s

.PHONY : src/client/HumanConsolePlayer.s

# target to generate assembly for a file
src/client/HumanConsolePlayer.cpp.s:
	$(MAKE) -f CMakeFiles/Reversi.dir/build.make CMakeFiles/Reversi.dir/src/client/HumanConsolePlayer.cpp.s
.PHONY : src/client/HumanConsolePlayer.cpp.s

src/client/Menu.o: src/client/Menu.cpp.o

.PHONY : src/client/Menu.o

# target to build an object file
src/client/Menu.cpp.o:
	$(MAKE) -f CMakeFiles/Reversi.dir/build.make CMakeFiles/Reversi.dir/src/client/Menu.cpp.o
.PHONY : src/client/Menu.cpp.o

src/client/Menu.i: src/client/Menu.cpp.i

.PHONY : src/client/Menu.i

# target to preprocess a source file
src/client/Menu.cpp.i:
	$(MAKE) -f CMakeFiles/Reversi.dir/build.make CMakeFiles/Reversi.dir/src/client/Menu.cpp.i
.PHONY : src/client/Menu.cpp.i

src/client/Menu.s: src/client/Menu.cpp.s

.PHONY : src/client/Menu.s

# target to generate assembly for a file
src/client/Menu.cpp.s:
	$(MAKE) -f CMakeFiles/Reversi.dir/build.make CMakeFiles/Reversi.dir/src/client/Menu.cpp.s
.PHONY : src/client/Menu.cpp.s

src/client/Player.o: src/client/Player.cpp.o

.PHONY : src/client/Player.o

# target to build an object file
src/client/Player.cpp.o:
	$(MAKE) -f CMakeFiles/Reversi.dir/build.make CMakeFiles/Reversi.dir/src/client/Player.cpp.o
.PHONY : src/client/Player.cpp.o

src/client/Player.i: src/client/Player.cpp.i

.PHONY : src/client/Player.i

# target to preprocess a source file
src/client/Player.cpp.i:
	$(MAKE) -f CMakeFiles/Reversi.dir/build.make CMakeFiles/Reversi.dir/src/client/Player.cpp.i
.PHONY : src/client/Player.cpp.i

src/client/Player.s: src/client/Player.cpp.s

.PHONY : src/client/Player.s

# target to generate assembly for a file
src/client/Player.cpp.s:
	$(MAKE) -f CMakeFiles/Reversi.dir/build.make CMakeFiles/Reversi.dir/src/client/Player.cpp.s
.PHONY : src/client/Player.cpp.s

src/client/Point.o: src/client/Point.cpp.o

.PHONY : src/client/Point.o

# target to build an object file
src/client/Point.cpp.o:
	$(MAKE) -f CMakeFiles/Reversi.dir/build.make CMakeFiles/Reversi.dir/src/client/Point.cpp.o
.PHONY : src/client/Point.cpp.o

src/client/Point.i: src/client/Point.cpp.i

.PHONY : src/client/Point.i

# target to preprocess a source file
src/client/Point.cpp.i:
	$(MAKE) -f CMakeFiles/Reversi.dir/build.make CMakeFiles/Reversi.dir/src/client/Point.cpp.i
.PHONY : src/client/Point.cpp.i

src/client/Point.s: src/client/Point.cpp.s

.PHONY : src/client/Point.s

# target to generate assembly for a file
src/client/Point.cpp.s:
	$(MAKE) -f CMakeFiles/Reversi.dir/build.make CMakeFiles/Reversi.dir/src/client/Point.cpp.s
.PHONY : src/client/Point.cpp.s

src/client/RemotePlayer.o: src/client/RemotePlayer.cpp.o

.PHONY : src/client/RemotePlayer.o

# target to build an object file
src/client/RemotePlayer.cpp.o:
	$(MAKE) -f CMakeFiles/Reversi.dir/build.make CMakeFiles/Reversi.dir/src/client/RemotePlayer.cpp.o
.PHONY : src/client/RemotePlayer.cpp.o

src/client/RemotePlayer.i: src/client/RemotePlayer.cpp.i

.PHONY : src/client/RemotePlayer.i

# target to preprocess a source file
src/client/RemotePlayer.cpp.i:
	$(MAKE) -f CMakeFiles/Reversi.dir/build.make CMakeFiles/Reversi.dir/src/client/RemotePlayer.cpp.i
.PHONY : src/client/RemotePlayer.cpp.i

src/client/RemotePlayer.s: src/client/RemotePlayer.cpp.s

.PHONY : src/client/RemotePlayer.s

# target to generate assembly for a file
src/client/RemotePlayer.cpp.s:
	$(MAKE) -f CMakeFiles/Reversi.dir/build.make CMakeFiles/Reversi.dir/src/client/RemotePlayer.cpp.s
.PHONY : src/client/RemotePlayer.cpp.s

src/client/VirtualPlayer.o: src/client/VirtualPlayer.cpp.o

.PHONY : src/client/VirtualPlayer.o

# target to build an object file
src/client/VirtualPlayer.cpp.o:
	$(MAKE) -f CMakeFiles/Reversi.dir/build.make CMakeFiles/Reversi.dir/src/client/VirtualPlayer.cpp.o
.PHONY : src/client/VirtualPlayer.cpp.o

src/client/VirtualPlayer.i: src/client/VirtualPlayer.cpp.i

.PHONY : src/client/VirtualPlayer.i

# target to preprocess a source file
src/client/VirtualPlayer.cpp.i:
	$(MAKE) -f CMakeFiles/Reversi.dir/build.make CMakeFiles/Reversi.dir/src/client/VirtualPlayer.cpp.i
.PHONY : src/client/VirtualPlayer.cpp.i

src/client/VirtualPlayer.s: src/client/VirtualPlayer.cpp.s

.PHONY : src/client/VirtualPlayer.s

# target to generate assembly for a file
src/client/VirtualPlayer.cpp.s:
	$(MAKE) -f CMakeFiles/Reversi.dir/build.make CMakeFiles/Reversi.dir/src/client/VirtualPlayer.cpp.s
.PHONY : src/client/VirtualPlayer.cpp.s

src/client/main.o: src/client/main.cpp.o

.PHONY : src/client/main.o

# target to build an object file
src/client/main.cpp.o:
	$(MAKE) -f CMakeFiles/Reversi.dir/build.make CMakeFiles/Reversi.dir/src/client/main.cpp.o
.PHONY : src/client/main.cpp.o

src/client/main.i: src/client/main.cpp.i

.PHONY : src/client/main.i

# target to preprocess a source file
src/client/main.cpp.i:
	$(MAKE) -f CMakeFiles/Reversi.dir/build.make CMakeFiles/Reversi.dir/src/client/main.cpp.i
.PHONY : src/client/main.cpp.i

src/client/main.s: src/client/main.cpp.s

.PHONY : src/client/main.s

# target to generate assembly for a file
src/client/main.cpp.s:
	$(MAKE) -f CMakeFiles/Reversi.dir/build.make CMakeFiles/Reversi.dir/src/client/main.cpp.s
.PHONY : src/client/main.cpp.s

src/server/CloseCommand.o: src/server/CloseCommand.cpp.o

.PHONY : src/server/CloseCommand.o

# target to build an object file
src/server/CloseCommand.cpp.o:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/server/CloseCommand.cpp.o
.PHONY : src/server/CloseCommand.cpp.o

src/server/CloseCommand.i: src/server/CloseCommand.cpp.i

.PHONY : src/server/CloseCommand.i

# target to preprocess a source file
src/server/CloseCommand.cpp.i:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/server/CloseCommand.cpp.i
.PHONY : src/server/CloseCommand.cpp.i

src/server/CloseCommand.s: src/server/CloseCommand.cpp.s

.PHONY : src/server/CloseCommand.s

# target to generate assembly for a file
src/server/CloseCommand.cpp.s:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/server/CloseCommand.cpp.s
.PHONY : src/server/CloseCommand.cpp.s

src/server/CommandsManager.o: src/server/CommandsManager.cpp.o

.PHONY : src/server/CommandsManager.o

# target to build an object file
src/server/CommandsManager.cpp.o:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/server/CommandsManager.cpp.o
.PHONY : src/server/CommandsManager.cpp.o

src/server/CommandsManager.i: src/server/CommandsManager.cpp.i

.PHONY : src/server/CommandsManager.i

# target to preprocess a source file
src/server/CommandsManager.cpp.i:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/server/CommandsManager.cpp.i
.PHONY : src/server/CommandsManager.cpp.i

src/server/CommandsManager.s: src/server/CommandsManager.cpp.s

.PHONY : src/server/CommandsManager.s

# target to generate assembly for a file
src/server/CommandsManager.cpp.s:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/server/CommandsManager.cpp.s
.PHONY : src/server/CommandsManager.cpp.s

src/server/JoinGameCommand.o: src/server/JoinGameCommand.cpp.o

.PHONY : src/server/JoinGameCommand.o

# target to build an object file
src/server/JoinGameCommand.cpp.o:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/server/JoinGameCommand.cpp.o
.PHONY : src/server/JoinGameCommand.cpp.o

src/server/JoinGameCommand.i: src/server/JoinGameCommand.cpp.i

.PHONY : src/server/JoinGameCommand.i

# target to preprocess a source file
src/server/JoinGameCommand.cpp.i:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/server/JoinGameCommand.cpp.i
.PHONY : src/server/JoinGameCommand.cpp.i

src/server/JoinGameCommand.s: src/server/JoinGameCommand.cpp.s

.PHONY : src/server/JoinGameCommand.s

# target to generate assembly for a file
src/server/JoinGameCommand.cpp.s:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/server/JoinGameCommand.cpp.s
.PHONY : src/server/JoinGameCommand.cpp.s

src/server/ListGamesCommand.o: src/server/ListGamesCommand.cpp.o

.PHONY : src/server/ListGamesCommand.o

# target to build an object file
src/server/ListGamesCommand.cpp.o:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/server/ListGamesCommand.cpp.o
.PHONY : src/server/ListGamesCommand.cpp.o

src/server/ListGamesCommand.i: src/server/ListGamesCommand.cpp.i

.PHONY : src/server/ListGamesCommand.i

# target to preprocess a source file
src/server/ListGamesCommand.cpp.i:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/server/ListGamesCommand.cpp.i
.PHONY : src/server/ListGamesCommand.cpp.i

src/server/ListGamesCommand.s: src/server/ListGamesCommand.cpp.s

.PHONY : src/server/ListGamesCommand.s

# target to generate assembly for a file
src/server/ListGamesCommand.cpp.s:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/server/ListGamesCommand.cpp.s
.PHONY : src/server/ListGamesCommand.cpp.s

src/server/PlayCommand.o: src/server/PlayCommand.cpp.o

.PHONY : src/server/PlayCommand.o

# target to build an object file
src/server/PlayCommand.cpp.o:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/server/PlayCommand.cpp.o
.PHONY : src/server/PlayCommand.cpp.o

src/server/PlayCommand.i: src/server/PlayCommand.cpp.i

.PHONY : src/server/PlayCommand.i

# target to preprocess a source file
src/server/PlayCommand.cpp.i:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/server/PlayCommand.cpp.i
.PHONY : src/server/PlayCommand.cpp.i

src/server/PlayCommand.s: src/server/PlayCommand.cpp.s

.PHONY : src/server/PlayCommand.s

# target to generate assembly for a file
src/server/PlayCommand.cpp.s:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/server/PlayCommand.cpp.s
.PHONY : src/server/PlayCommand.cpp.s

src/server/Server.o: src/server/Server.cpp.o

.PHONY : src/server/Server.o

# target to build an object file
src/server/Server.cpp.o:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/server/Server.cpp.o
.PHONY : src/server/Server.cpp.o

src/server/Server.i: src/server/Server.cpp.i

.PHONY : src/server/Server.i

# target to preprocess a source file
src/server/Server.cpp.i:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/server/Server.cpp.i
.PHONY : src/server/Server.cpp.i

src/server/Server.s: src/server/Server.cpp.s

.PHONY : src/server/Server.s

# target to generate assembly for a file
src/server/Server.cpp.s:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/server/Server.cpp.s
.PHONY : src/server/Server.cpp.s

src/server/StartCommand.o: src/server/StartCommand.cpp.o

.PHONY : src/server/StartCommand.o

# target to build an object file
src/server/StartCommand.cpp.o:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/server/StartCommand.cpp.o
.PHONY : src/server/StartCommand.cpp.o

src/server/StartCommand.i: src/server/StartCommand.cpp.i

.PHONY : src/server/StartCommand.i

# target to preprocess a source file
src/server/StartCommand.cpp.i:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/server/StartCommand.cpp.i
.PHONY : src/server/StartCommand.cpp.i

src/server/StartCommand.s: src/server/StartCommand.cpp.s

.PHONY : src/server/StartCommand.s

# target to generate assembly for a file
src/server/StartCommand.cpp.s:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/server/StartCommand.cpp.s
.PHONY : src/server/StartCommand.cpp.s

src/server/ThreadPool.o: src/server/ThreadPool.cpp.o

.PHONY : src/server/ThreadPool.o

# target to build an object file
src/server/ThreadPool.cpp.o:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/server/ThreadPool.cpp.o
.PHONY : src/server/ThreadPool.cpp.o

src/server/ThreadPool.i: src/server/ThreadPool.cpp.i

.PHONY : src/server/ThreadPool.i

# target to preprocess a source file
src/server/ThreadPool.cpp.i:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/server/ThreadPool.cpp.i
.PHONY : src/server/ThreadPool.cpp.i

src/server/ThreadPool.s: src/server/ThreadPool.cpp.s

.PHONY : src/server/ThreadPool.s

# target to generate assembly for a file
src/server/ThreadPool.cpp.s:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/server/ThreadPool.cpp.s
.PHONY : src/server/ThreadPool.cpp.s

src/server/gameLoopTask.o: src/server/gameLoopTask.cpp.o

.PHONY : src/server/gameLoopTask.o

# target to build an object file
src/server/gameLoopTask.cpp.o:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/server/gameLoopTask.cpp.o
.PHONY : src/server/gameLoopTask.cpp.o

src/server/gameLoopTask.i: src/server/gameLoopTask.cpp.i

.PHONY : src/server/gameLoopTask.i

# target to preprocess a source file
src/server/gameLoopTask.cpp.i:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/server/gameLoopTask.cpp.i
.PHONY : src/server/gameLoopTask.cpp.i

src/server/gameLoopTask.s: src/server/gameLoopTask.cpp.s

.PHONY : src/server/gameLoopTask.s

# target to generate assembly for a file
src/server/gameLoopTask.cpp.s:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/server/gameLoopTask.cpp.s
.PHONY : src/server/gameLoopTask.cpp.s

src/server/server_main.o: src/server/server_main.cpp.o

.PHONY : src/server/server_main.o

# target to build an object file
src/server/server_main.cpp.o:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/server/server_main.cpp.o
.PHONY : src/server/server_main.cpp.o

src/server/server_main.i: src/server/server_main.cpp.i

.PHONY : src/server/server_main.i

# target to preprocess a source file
src/server/server_main.cpp.i:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/server/server_main.cpp.i
.PHONY : src/server/server_main.cpp.i

src/server/server_main.s: src/server/server_main.cpp.s

.PHONY : src/server/server_main.s

# target to generate assembly for a file
src/server/server_main.cpp.s:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/server/server_main.cpp.s
.PHONY : src/server/server_main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... Reversi"
	@echo "... server"
	@echo "... src/client/AIPlayer.o"
	@echo "... src/client/AIPlayer.i"
	@echo "... src/client/AIPlayer.s"
	@echo "... src/client/BasicGameRules.o"
	@echo "... src/client/BasicGameRules.i"
	@echo "... src/client/BasicGameRules.s"
	@echo "... src/client/Board.o"
	@echo "... src/client/Board.i"
	@echo "... src/client/Board.s"
	@echo "... src/client/ConsoleDisplay.o"
	@echo "... src/client/ConsoleDisplay.i"
	@echo "... src/client/ConsoleDisplay.s"
	@echo "... src/client/GamePlay.o"
	@echo "... src/client/GamePlay.i"
	@echo "... src/client/GamePlay.s"
	@echo "... src/client/GameRules.o"
	@echo "... src/client/GameRules.i"
	@echo "... src/client/GameRules.s"
	@echo "... src/client/HumanConsolePlayer.o"
	@echo "... src/client/HumanConsolePlayer.i"
	@echo "... src/client/HumanConsolePlayer.s"
	@echo "... src/client/Menu.o"
	@echo "... src/client/Menu.i"
	@echo "... src/client/Menu.s"
	@echo "... src/client/Player.o"
	@echo "... src/client/Player.i"
	@echo "... src/client/Player.s"
	@echo "... src/client/Point.o"
	@echo "... src/client/Point.i"
	@echo "... src/client/Point.s"
	@echo "... src/client/RemotePlayer.o"
	@echo "... src/client/RemotePlayer.i"
	@echo "... src/client/RemotePlayer.s"
	@echo "... src/client/VirtualPlayer.o"
	@echo "... src/client/VirtualPlayer.i"
	@echo "... src/client/VirtualPlayer.s"
	@echo "... src/client/main.o"
	@echo "... src/client/main.i"
	@echo "... src/client/main.s"
	@echo "... src/server/CloseCommand.o"
	@echo "... src/server/CloseCommand.i"
	@echo "... src/server/CloseCommand.s"
	@echo "... src/server/CommandsManager.o"
	@echo "... src/server/CommandsManager.i"
	@echo "... src/server/CommandsManager.s"
	@echo "... src/server/JoinGameCommand.o"
	@echo "... src/server/JoinGameCommand.i"
	@echo "... src/server/JoinGameCommand.s"
	@echo "... src/server/ListGamesCommand.o"
	@echo "... src/server/ListGamesCommand.i"
	@echo "... src/server/ListGamesCommand.s"
	@echo "... src/server/PlayCommand.o"
	@echo "... src/server/PlayCommand.i"
	@echo "... src/server/PlayCommand.s"
	@echo "... src/server/Server.o"
	@echo "... src/server/Server.i"
	@echo "... src/server/Server.s"
	@echo "... src/server/StartCommand.o"
	@echo "... src/server/StartCommand.i"
	@echo "... src/server/StartCommand.s"
	@echo "... src/server/ThreadPool.o"
	@echo "... src/server/ThreadPool.i"
	@echo "... src/server/ThreadPool.s"
	@echo "... src/server/gameLoopTask.o"
	@echo "... src/server/gameLoopTask.i"
	@echo "... src/server/gameLoopTask.s"
	@echo "... src/server/server_main.o"
	@echo "... src/server/server_main.i"
	@echo "... src/server/server_main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

